question_data = [
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "text": "Igneous rocks are formed by excessive heat and pressure.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "text": "A slug's blood is green.", "answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "text": "The Cold War ended with Joseph Stalin's death.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "The song 'Megalovania' by Toby Fox made its third appearance in the 2015 RPG 'Undertale'.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "text": "Manchester United won the 2013-14 English Premier League.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "text": "Eurobeat is primarily an Italian genre of music.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "text": "The logo for Snapchat is a Bell.", "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "text": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "text": "There is a city called Rome in every continent on Earth.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "The game 'Battlefield 1' takes place during World War I.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy",
     "text": "The anime 'Lucky Star' follows the story of one girl who is unaware she is God.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "text": "You can legally drink alcohol while driving in Mississippi.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy", "text": "No Game No Life first aired in 2014.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "The ultimate phrase used by Pharah from Overwatch is: 'Justice rains from above!'",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film",
     "type": "boolean", "difficulty": "easy",
     "text": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Samuel L. Jackson had the words, 'Bad Motherf*cker' in-scripted on his lightsaber during the "
             "filming of Star Wars.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy",
     "text": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "text": "Toronto is the capital city of the North American country of Canada.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "The main playable character of the 2015 RPG 'Undertale' is a monster.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "text": "A flock of crows is known as a homicide.", "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "text": "When you cry in space, your tears stick to your face.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "text": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
     "text": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "text": "The Windows 7 operating system has six main editions.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "text": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and "
             "Italian. ",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "In Pokemon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "text": "Daft Punk originated in France.", "answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
     "text": "Marilyn Monroe was born on July 1, 1926.", "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "In 'Undertale', the main character of the game is Sans.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "text": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "text": "In 'Star Trek', Klaang is a typical Klingon male.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Art", "type": "boolean", "difficulty": "easy",
     "text": "Leonardo da Vinci was not the creator of the Mona Lisa.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
     "difficulty": "easy",
     "text": "Waylon Smithers from 'The Simpsons' was originally black when he first appeared in the series.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Actor Tommy Chong served prison time.", "answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "text": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming "
             "pools and drinking water.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "text": "New Haven is the capital city of the state of Connecticut in the United States.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "text": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party "
             "in 1912.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "In 'Need for Speed: Porsche Unleashed', the player can only drive cars manufactured by Porsche.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "text": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his "
             "contract with Warner Bros.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "text": "Rhode Island is actually located on the US mainland, despite its name.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "text": "A scalene triangle has two sides of equal length.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "text": "There is an island in Japan called Okunoshima, A.K.A. 'Rabbit Island', so named because of it's "
             "huge population of rabbits.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "text": "Rabbits are carnivores.", "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "text": "'The Simpsons' family is named after creator Matt Groening's real family.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final "
             "chapter of the game.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "text": "The shotgun appears in every numbered Resident Evil game.",
     "answer": "True", "incorrect_answers": ["False"]}
]
